AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/**/*'
    - 'config/*'
    - 'bin/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Metrics/MethodLength:
  Exclude:
    - 'spec/support/**'
