AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/**/*'
    - 'config/*'
    - 'bin/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Metrics/ClassLength:
  Exclude:
    - 'app/models/user.rb'
Metrics/ModuleLength:
  Exclude:
    - 'spec/support/**'
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/support/**'
    - 'app/controllers/challenge_finalizations_controller.rb'
Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/support/**'
    - 'app/controllers/challenge_finalizations_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/controllers/tasks_controller.rb'
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
Style/GuardClause:
  Exclude:
    - 'app/models/user.rb'
    - 'app/models/odds_are.rb'
    - 'app/controllers/notifications_controller.rb'
    - 'app/controllers/odds_ares_controller.rb'
    - 'app/controllers/tasks_controller.rb'
    - 'app/services/users/check_friendship_service.rb'
