# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
    working_directory: ~/odds_are

    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin

      - run:
          name: Install Docker-Compose client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Compose docker environment
          command: docker-compose up -d

      - run:
          name: Database setup
          command: |
            docker exec oddsare_web_1 bin/rails db:create RAILS_ENV=test --trace
            docker exec oddsare_web_1 bin/rails db:migrate RAILS_ENV=test

      - run:
          name: Execute unit tests
          command: docker exec oddsare_web_1 bundle exec rspec

      - run:
          name: Code analysis
          command: docker exec oddsare_web_1 rubocop
